[0m11:02:32.092678 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F8E0CBF9D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F8E35E1F60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F8E35E1D80>]}


============================== 11:02:32.101678 | d9854393-86ca-4182-8c00-d986f46a4360 ==============================
[0m11:02:32.101678 [info ] [MainThread]: Running with dbt=1.8.5
[0m11:02:32.103681 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Oamen\\.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt init', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m11:03:00.741331 [debug] [MainThread]: Starter project path: C:\Users\Oamen\anaconda3\lib\site-packages\dbt\include\starter_project
[0m11:03:00.803680 [info ] [MainThread]: 
Your new dbt project "cus_subscription_pipeline" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m11:03:00.806680 [info ] [MainThread]: Setting up your profile.
[0m11:05:23.337708 [info ] [MainThread]: Profile cus_subscription_pipeline written to C:\Users\Oamen\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m11:05:23.343708 [debug] [MainThread]: Command `dbt init` succeeded at 11:05:23.343708 after 171.40 seconds
[0m11:05:23.346738 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F8E0CBF9D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F8E35E1ED0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F8F4428970>]}
[0m11:05:23.349730 [debug] [MainThread]: Flushing usage events
[0m11:05:30.229101 [debug] [MainThread]: Error sending anonymous usage statistics. Disabling tracking for this execution. If you wish to permanently disable tracking, see: https://docs.getdbt.com/reference/global-configs#send-anonymous-usage-stats.
[0m11:05:39.148899 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018F0579FA30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018F080C1FC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018F080C1DE0>]}


============================== 11:05:39.157331 | 00f220fb-0e91-40ba-b63c-3f02243b0286 ==============================
[0m11:05:39.157331 [info ] [MainThread]: Running with dbt=1.8.5
[0m11:05:39.158971 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': 'C:\\Users\\Oamen\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'invocation_command': 'dbt debug', 'send_anonymous_usage_stats': 'True'}
[0m11:05:39.205958 [info ] [MainThread]: dbt version: 1.8.5
[0m11:05:39.206347 [info ] [MainThread]: python version: 3.10.9
[0m11:05:39.208355 [info ] [MainThread]: python path: C:\Users\Oamen\anaconda3\python.exe
[0m11:05:39.209358 [info ] [MainThread]: os info: Windows-10-10.0.22631-SP0
[0m11:05:43.442094 [info ] [MainThread]: Using profiles dir at C:\Users\Oamen\.dbt
[0m11:05:43.443162 [info ] [MainThread]: Using profiles.yml file at C:\Users\Oamen\.dbt\profiles.yml
[0m11:05:43.444754 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\Oamen\OneDrive\Documents\DATA PROJECTS\customer_subscription_elt_pipeline\dbt_project.yml
[0m11:05:43.446398 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m11:05:43.449433 [debug] [MainThread]: Command `dbt debug` failed at 11:05:43.448861 after 4.44 seconds
[0m11:05:43.451047 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018F0579FA30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018F18F2EC20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018F1908B1F0>]}
[0m11:05:43.452194 [debug] [MainThread]: Flushing usage events
[0m12:48:16.053015 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000211FFF1FA90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002118314A140>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021183149F60>]}


============================== 12:48:16.061893 | 983ca491-a958-437d-a60f-f4c59a8b200b ==============================
[0m12:48:16.061893 [info ] [MainThread]: Running with dbt=1.8.5
[0m12:48:16.064501 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\Oamen\\.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m12:48:16.065573 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Oamen\OneDrive\Documents\DATA PROJECTS\customer_subscription_elt_pipeline\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:48:16.067119 [debug] [MainThread]: Command `dbt run` failed at 12:48:16.067119 after 0.26 seconds
[0m12:48:16.068119 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000211FFF1FA90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021183149E70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002118314A1D0>]}
[0m12:48:16.069120 [debug] [MainThread]: Flushing usage events
[0m18:48:17.799921 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024B829AFA90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024B85302260>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024B85302080>]}


============================== 18:48:17.812470 | b2432f80-95cc-454d-a17d-fa5670a09dc0 ==============================
[0m18:48:17.812470 [info ] [MainThread]: Running with dbt=1.8.5
[0m18:48:17.814469 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': 'C:\\Users\\Oamen\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'invocation_command': 'dbt docs generate', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m18:48:17.815987 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Oamen\OneDrive\Documents\DATA PROJECTS\customer_subscription_elt_pipeline\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m18:48:17.818501 [debug] [MainThread]: Command `dbt docs generate` failed at 18:48:17.818501 after 0.29 seconds
[0m18:48:17.819538 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024B829AFA90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024B85301F90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024B853022F0>]}
[0m18:48:17.820507 [debug] [MainThread]: Flushing usage events
